### ISSUE TITLE
missing module './config'

### ISSUE THREAD

**Issue by pjz** [jackson-jackson/otweb#1]
I tried:

```
pj@trireme:~/src/otweb$ coffee app.coffee
```

and got:

```
Error: Cannot find module './config'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/pj/src/otweb/app.coffee:1:10)
  at Object.<anonymous> (/home/pj/src/otweb/app.coffee:1:1)
  at Module._compile (module.js:456:26)
```

...what did I forget?

**Comment by ben-haim** [comment]
Did you manage to fix this issue ? tks

**Comment by pjz** [comment]
I don't think I did.

**Comment by jackson-jackson** [comment]
Hello, gents. I've been away for some time working on other projects, but now that opentxs and money changer seem to be back in full development I'm going to devote some time to this! Stay tuned for updates.
